const modules=['Dashboard','Jobs','Operatives','Timesheets','Plant & Vehicles','Documents','Forms & Inspections','Photos','Reports','Settings'];let index=0;
const quick=['New Job','Add Operative','Approve Timesheets','Book Plant','Start Inspection','Add Photos','Generate Report','Create Invoice','Send Handover'];
function renderNav(){sideNav.innerHTML=modules.map((m,i)=>`<div class="navitem ${i===index?'active':''}"><span>${m}</span><span class="badge">${i===index?'Viewing':'Preview'}</span></div>`).join('')}
function kpis(){kpiSection.innerHTML=[['Active Jobs','147','Live tracker'],['Operatives Today','83','8 crews active'],['Work Delivered','£28k','Today'],['Starting Today','6','Pre-start ready'],['Finishing Today','4','Handover due'],['Overdue Jobs','7','Needs follow-up']].map(x=>`<div class="kpi rounded-2xl p-4"><div class="text-xs uppercase tracking-widest font-black text-[#06452f]/80">${x[0]}</div><div class="text-4xl font-black text-[#06452f] mt-2">${x[1]}</div><div class="text-sm font-bold text-[#06452f]/80">${x[2]}</div></div>`).join('')}
function quicks(){quickActions.innerHTML=quick.map((q,i)=>`<div class="${i%3===0?'green-btn':i%5===0?'gold-btn':'ghost-btn'} text-center opacity-95">${q}<br><span class="text-[10px] uppercase tracking-widest opacity-70">Preview result</span></div>`).join('')}
function status(s){return s==='Active'?'bg-green-100 text-green-800':s==='RAMS Needed'?'bg-yellow-100 text-yellow-800':s==='Quote Sent'?'bg-blue-100 text-blue-800':'bg-slate-100 text-slate-700'}
const jobs=[['MAR-0246','Story Homes','Strawberry Grange','Daniel Wignall','Active','£48,750'],['MAR-0247','Gleeson Homes','Calluna Grange','Lee Park','Active','£36,200'],['MAR-0248','Home Group','Workington Rd','Antony Pearson','RAMS Needed','£22,800'],['MAR-0249','Thomas Armstrong','Harrington Park','Daniel Wignall','Active','£31,500'],['MAR-0250','Genesis Homes','Farnell Park','Lee Park','Quote Sent','£17,450']];
function table(rows=jobs){return `<div class="overflow-x-auto rounded-2xl border"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="text-left px-4 py-3">Job No</th><th class="text-left px-4 py-3">Client</th><th class="text-left px-4 py-3">Site</th><th class="text-left px-4 py-3">Supervisor</th><th class="text-left px-4 py-3">Status</th><th class="text-left px-4 py-3">Value</th></tr></thead><tbody class="divide-y divide-slate-100">${rows.map(j=>`<tr><td class="px-4 py-3 font-bold">${j[0]}</td><td class="px-4 py-3">${j[1]}</td><td class="px-4 py-3">${j[2]}</td><td class="px-4 py-3">${j[3]}</td><td class="px-4 py-3"><span class="pill ${status(j[4])}">${j[4]}</span></td><td class="px-4 py-3">${j[5]}</td></tr>`).join('')}</tbody></table></div>`}
const scene={
Dashboard:['Dashboard Overview','The command center for active jobs, crews, sites, and work delivery.',()=>`<div class="gridMain grid gap-6"><div>${table()}</div><div class="rounded-2xl bg-slate-50 p-5 border"><div class="flex justify-between"><b>Job Status</b><span class="pill bg-yellow-100 text-yellow-900">Live</span></div><div class="mt-5 flex gap-5 items-center"><div class="relative w-36 h-36"><div class="ring absolute inset-0 rounded-full"></div><div class="absolute inset-[25%] bg-white rounded-full grid place-items-center text-center"><b class="text-3xl text-[#06452f]">147</b></div></div><div class="text-sm space-y-2 flex-1"><p>Active: <b>92</b></p><p>RAMS Needed: <b>18</b></p><p>Quote Sent: <b>16</b></p><p>On Hold: <b>11</b></p></div></div></div></div>`],
Jobs:['Jobs Module','Shows the job list, search filters, selected job details, and a new-job drawer state.',()=>`<div class="grid lg:grid-cols-[1.2fr_.8fr] gap-5"><div><div class="flex gap-3 mb-4"><div class="ghost-btn flex-1 text-left">Search jobs, sites, clients</div><div class="gold-btn">Create Job</div></div>${table()}</div><div class="rounded-2xl bg-slate-50 p-5 border"><b>New Job Drawer Open</b><div class="mt-4 space-y-3"><div class="bg-white rounded-xl p-3 border">Client: Story Homes</div><div class="bg-white rounded-xl p-3 border">Site: Strawberry Grange</div><div class="bg-white rounded-xl p-3 border">Supervisor: Daniel Wignall</div><div class="bg-white rounded-xl p-3 border">Status: Draft ready to save</div></div></div></div>`],
Operatives:['Operatives Module','Crew allocation, attendance, certification, and site assignments in one view.',()=>`<div class="grid md:grid-cols-4 gap-4">${['Daniel Wignall','Lee Park','Antony Pearson','James Carter'].map((n,i)=>`<div class="rounded-2xl bg-slate-50 p-5 border"><div class="h-12 w-12 rounded-full bg-[#06452f] text-white grid place-items-center font-black">${n[0]}</div><b class="block mt-3">${n}</b><p class="text-sm text-slate-500">${i+2} jobs today</p><div class="mt-3 pill bg-green-100 text-green-800">On site</div></div>`).join('')}</div>`],
Timesheets:['Timesheets Module','Pending approvals, daily hours, payroll review, and supervisor confirmations.',()=>`<div class="grid lg:grid-cols-[1fr_.7fr] gap-5"><div class="overflow-x-auto rounded-2xl border"><table class="min-w-full text-sm"><thead class="bg-slate-50"><tr><th class="text-left p-3">Operative</th><th class="text-left p-3">Hours</th><th class="text-left p-3">Site</th><th class="text-left p-3">Review State</th></tr></thead><tbody>${['Daniel Wignall','Lee Park','Antony Pearson','James Carter'].map((n,i)=>`<tr class="border-t"><td class="p-3 font-bold">${n}</td><td class="p-3">${8+i}.0</td><td class="p-3">${jobs[i%jobs.length][2]}</td><td class="p-3"><span class="pill bg-yellow-100 text-yellow-800">Approve</span></td></tr>`).join('')}</tbody></table></div><div class="rounded-2xl bg-slate-50 p-5 border"><b>Approval Summary</b><p class="text-4xl font-black text-[#06452f] mt-4">32.5h</p><p class="text-sm text-slate-600">Selected timesheets ready for approval.</p></div></div>`],
'Plant & Vehicles':['Plant & Vehicles Module','Equipment bookings, vehicle inspection states, and plant availability.',()=>`<div class="grid md:grid-cols-3 gap-4">${['Wagon 1','Wagon 2','Scaffold Kit A','Forklift 4','Harness Set','Wagon 3'].map((x,i)=>`<div class="rounded-2xl bg-slate-50 p-5 border"><b>${x}</b><p class="text-sm text-slate-500 mt-1">${i%2?'Inspection due':'Ready for dispatch'}</p><div class="mt-4 h-2 bg-white rounded-full"><div class="h-2 rounded-full ${i%2?'bg-yellow-400 w-2/3':'bg-[#06452f] w-full'}"></div></div></div>`).join('')}</div>`],
Documents:['Documents Module','RAMS, insurance records, handover files, and document pack generation.',()=>`<div class="grid lg:grid-cols-2 gap-4"><div class="rounded-2xl bg-slate-50 p-5 border"><b>Document Library</b><div class="mt-3 space-y-2 text-sm">${['RAMS Pack — MAR-0248','Insurance Certificate','Client Handover Template','Scaffold Inspection Record'].map(x=>`<div class="bg-white border rounded-xl p-3">${x}</div>`).join('')}</div></div><div class="rounded-2xl bg-slate-50 p-5 border"><b>Generated Pack Preview</b><div class="mt-4 bg-white border rounded-xl p-4"><p>RAMS + Handover + Site Photos</p><p class="text-sm text-slate-500 mt-2">Ready to send to client after approval.</p></div></div></div>`],
'Forms & Inspections':['Forms & Inspections Module','Safety checklist, completion progress, and inspection evidence.',()=>`<div class="rounded-2xl bg-slate-50 p-5 border"><b>RAMS / Site Inspection Checklist</b><div class="mt-4 grid sm:grid-cols-2 gap-3">${['PPE confirmed','Scaffold tags checked','Access route safe','Weather logged','Photos attached','Client sign-off ready'].map((x,i)=>`<div class="bg-white rounded-xl border p-3 flex gap-3"><span class="h-5 w-5 rounded border ${i<4?'bg-[#06452f]':''}"></span><span>${x}</span></div>`).join('')}</div><div class="mt-4 h-3 bg-white rounded-full overflow-hidden"><div class="h-full bg-[#06452f] w-[67%]"></div></div></div>`],
Photos:['Photos Module','Site photo gallery with before, during, and after documentation states.',()=>`<div class="grid lg:grid-cols-[.75fr_1.25fr] gap-4"><div class="rounded-2xl bg-slate-50 p-5 border"><b>Photo Evidence Log</b><p class="text-sm text-slate-600 mt-2">Photos grouped by site, job, and handover stage.</p><div class="gold-btn mt-4 inline-block">Upload area visible</div></div><div class="grid sm:grid-cols-3 gap-3">${['Before','Access','In Progress','Tagged','Handover','Signed Off'].map((x,i)=>`<div class="h-32 rounded-2xl ${i%2?'bg-slate-300':'bg-slate-200'} grid place-items-center font-bold text-slate-600">${x}</div>`).join('')}</div></div>`],
Reports:['Reports Module','Output charts, status summaries, revenue snapshots, and delivery analytics.',()=>`<div class="grid lg:grid-cols-3 gap-4"><div class="rounded-2xl bg-slate-50 p-5 border"><b>Daily Output</b><p class="text-3xl font-black text-[#06452f] mt-3">£28,450</p></div><div class="rounded-2xl bg-slate-50 p-5 border"><b>Open Quotes</b><p class="text-3xl font-black text-[#06452f] mt-3">16</p></div><div class="rounded-2xl bg-slate-50 p-5 border"><b>Overdue Work</b><p class="text-3xl font-black text-red-600 mt-3">7</p></div><div class="lg:col-span-3 rounded-2xl bg-slate-50 p-5 border"><b>Work Delivered Chart</b><div class="bars mt-6 h-44 flex items-end justify-around">${[44,54,66,58,82,76,96].map(h=>`<div style="height:${h}%;width:28px"></div>`).join('')}</div></div></div>`],
Settings:['Settings Module','Notification rules, automation preferences, team settings, and approval logic.',()=>`<div class="grid md:grid-cols-3 gap-4">${['Client portal','Email reminders','Invoice automation','Crew notifications','Photo proof required','Weekly report'].map((x,i)=>`<div class="rounded-2xl bg-slate-50 p-5 border flex justify-between gap-4"><b>${x}</b><span class="h-6 w-11 rounded-full ${i<5?'bg-[#06452f]':'bg-slate-300'} relative"><span class="absolute top-1 ${i<5?'right-1':'left-1'} h-4 w-4 rounded-full bg-white"></span></span></div>`).join('')}</div>`]
};
function renderScene(){let m=modules[index];let s=scene[m];currentModuleTop.textContent=m;sceneTitle.textContent=s[0];sceneCaption.textContent=s[1];sceneBody.classList.remove('fade');void sceneBody.offsetWidth;sceneBody.classList.add('fade');sceneBody.innerHTML=s[2]();renderNav();dots.innerHTML=modules.map((m,i)=>`<span class="progress-dot ${i===index?'active':''}"></span>`).join('')}
function cycle(){index=(index+1)%modules.length;renderScene()}
kpis();quicks();renderScene();setInterval(cycle,5200);